# Para Google Cloud App Engine
runtime: python313

automatic_scaling:
  max_instances: 3
  min_instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  PYTHONUNBUFFERED: "1"
  FASTAPI_ENV: "production"

# Permitir archivos grandes
handlers:
  - url: /.*
    script: auto
    upload: 500mb
    secure: always
    redirect_http_response_code: 301
